export const RESET_CONTACT_STATE = "RESET_CONTACT_STATE";
export const SET_CONTACT_ERROR = "SET_CONTACT_ERROR";
export const SET_CONTACT_LOADING = "SET_CONTACT_LOADING";
export const SET_CONTACT_SUCCESS = "SET_CONTACT_SUCCESS";
export const TOGGLE_MENU = "TOGGLE_MENU";
